### ISSUE TITLE
Runtime error when updating http4s from 0.23.12 to 0.23.13

### ISSUE THREAD

**Issue by hruoho** [http4s/http4s#6933]
We have pinned `http4s` version to `0.23.12`. There are three dependencies which share the common version - `http4s-blaze-client`, `http4s-dsl` and `http4s-scala-xml`.

Trying to update from 0.23.12 to 0.23.13 results in the following error:

```
java.lang.NoSuchMethodError: org.http4s.Platform$.loggerFactory()Lorg/typelevel/log4cats/LoggerFactory;
	at org.http4s.client.middleware.Retry$.<init>(Retry.scala:39)
	at org.http4s.client.middleware.Retry$.<clinit>(Retry.scala)
	at org.http4s.blaze.client.BlazeClient$.makeClient(BlazeClient.scala:64)
	at org.http4s.blaze.client.BlazeClientBuilder.$anonfun$resourceWithState$6(BlazeClientBuilder.scala:346)
```

We are able to circumvent the problem by bumping `http4s-dsl` to `0.23.16` but it seems risky to use mismatching versions of the libraries.

```
<dependency>
 <groupId>org.http4s</groupId>
 <artifactId>http4s-blaze-client_2.12</artifactId>
 <version>0.23.13</version>
</dependency>
<dependency>
 <groupId>org.http4s</groupId>
 <artifactId>http4s-dsl_2.12</artifactId>
 <version>0.23.16</version> <!-- must be 0.23.16+ to avoid log4cats error -->
</dependency>
<dependency>
 <groupId>org.http4s</groupId>
 <artifactId>http4s-scala-xml_2.12</artifactId>
 <version>0.23.13</version>
</dependency>
``` 

Running `mvn dependency:tree` shows the following:
```
+- org.http4s:http4s-blaze-client_2.12:jar:0.23.13:compile
|  +- org.http4s:http4s-blaze-core_2.12:jar:0.23.13:compile
|  |  \- org.http4s:blaze-http_2.12:jar:0.23.13:compile
|  |     +- org.http4s:blaze-core_2.12:jar:0.23.13:compile
|  |     \- com.twitter:hpack:jar:1.0.2:compile
|  \- org.http4s:http4s-client_2.12:jar:0.23.16:compile
+- org.http4s:http4s-dsl_2.12:jar:0.23.13:compile
|  \- org.http4s:http4s-core_2.12:jar:0.23.13:compile
|     +- org.typelevel:case-insensitive_2.12:jar:1.2.0:compile
|     +- org.typelevel:cats-core_2.12:jar:2.8.0:compile
|     |  \- org.typelevel:cats-kernel_2.12:jar:2.8.0:compile
|     +- org.typelevel:cats-effect-std_2.12:jar:3.3.12:compile
|     |  \- org.typelevel:cats-effect-kernel_2.12:jar:3.3.12:compile
|     +- org.typelevel:cats-parse_2.12:jar:0.3.7:compile
|     +- org.http4s:http4s-crypto_2.12:jar:0.2.3:compile
|     +- co.fs2:fs2-core_2.12:jar:3.2.8:compile
|     |  \- org.typelevel:cats-effect_2.12:jar:3.3.12:compile
|     +- co.fs2:fs2-io_2.12:jar:3.2.8:compile
|     +- com.comcast:ip4s-core_2.12:jar:3.1.3:compile
|     +- org.typelevel:literally_2.12:jar:1.0.2:compile
|     +- org.scodec:scodec-bits_2.12:jar:1.1.34:compile
|     \- org.typelevel:vault_2.12:jar:3.2.1:compile
+- org.http4s:http4s-scala-xml_2.12:jar:0.23.13:compile
```

**Comment by armanbilge** [comment]
> Trying to update from 0.23.12 to 0.23.13 results in the following error:

You need to add `http4s-client` 0.23.13 to your dependency list to make the error go away.

**Comment by armanbilge** [comment]
> but it seems risky to use mismatching versions of the libraries.

It's not risky, it's normal. The versions are not supposed to match anymore (the same way the Cats, Cats Effect, or FS2 versions don't match the http4s version).

It is explained here:

> Be aware that versions of these modules will be untethered from the core version they depend on.
>
> - These modules may not be republished with each core patch release, but will still work on the latest 0.23 core.

https://github.com/http4s/http4s/releases/tag/v0.23.12

It is far more risky to stay on an old version with known, public security vulnerabilities.

**Comment by hruoho** [comment]
Thank you! Will close this now.
