### ISSUE TITLE
Middleware composability

### ISSUE THREAD

**Issue by gvolpe** [http4s/http4s#1967]
Following this [Gitter discussion](https://gitter.im/http4s/http4s?at=5b5fbe6820d248394f690d58) with @rossabaker I'm opening this issue to further discuss the current situation about middleware composition.

In v0.19.x all the middlewares became more polymorphic in their type signature having some that play well with `HttpRoutes[F]` and some others that fit better the `HttpApp[F]` shape. Whereas in v0.18.x all the middlewares have the shape `HttpService[F] => HttpService[F]` making composition very trivial.

Although the separation of concerns sounds very good in theory when it comes to use it in real use cases we can identify some flaws in composition (or at least very confusing). 

Eg. the following snippet does not compile on v0.19.x:

```scala
import cats.effect.{Concurrent, Timer}
import org.http4s.implicits._
import org.http4s.server.middleware.{AutoSlash, CORS, Timeout}
import org.http4s.{HttpApp, HttpRoutes}

import scala.concurrent.duration._

class Module[F[_]: Concurrent: Timer] {

  type HttpMiddleware = HttpRoutes[F] => HttpRoutes[F]

  val middle: HttpMiddleware = {
    { http: HttpRoutes[F] =>
      AutoSlash(http)
    } compose { http: HttpRoutes[F] =>
      CORS(http, CORS.DefaultCORSConfig)
    } compose { http: HttpRoutes[F] =>
      Timeout(2.seconds)(http)
    }
  }

  val httpApp: HttpApp[F] = httpRoutes.orNotFound

}
```

In this case the `Timeout` middleware requires an instance of `Timer[OptionT[F, ?]]` where all we have is an instance of `Timer[F]` as specified in the `Module` class type signature.

The error reported is the following:

```
[error] /workspace/http4s-demo/examples/src/main/scala/demo/Module.scala:52:25: Cannot find implicit value for Timer[[A]cats.data.OptionT[F,A]].
[error] Note that [A]cats.data.OptionT[F,A] needs to be a cats.effect.Async data type. You might also
[error] need a scala.concurrent.ExecutionContext in scope, or equivalent, try to
[error] import scala.concurrent.ExecutionContext.Implicits.global
[error]       Timeout(2.seconds)(http)

[error]                         ^
[error] one error found
[error] (examples / Compile / compileIncremental) Compilation failed
[error] Total time: 5 s, completed Jul 31, 2018 1:03:21 PM
```

Similarly, if we take this in isolation, the error remains the same:

```scala
val middle: HttpMiddleware = {
  { http: HttpRoutes[F] =>
    Timeout(2.seconds)(http)
  }
}
```

### Conclusion

It all leads to believe that `Timeout` fits better the middleware shape `HttpApp[F] => HttpApp[F]` as demonstrated below (this compiles):

```scala
type HttpMiddleware = HttpApp[F] => HttpApp[F]

val middle: HttpMiddleware = {
  { http: HttpApp[F] =>
    Timeout(2.seconds)(http)
  }
}
```

### Steps forward

I haven't played much with other middlewares but my gut feeling is that there might be other similar cases where composition is just not possible and this is one the features I love the most in v0.18.x.

I would like to hear your thoughts and discuss what's best in order to make a nice final 1.0 version.

**Comment by yoohaemin** [comment]
Would documentation and type aliases that clearly distinguishes which middleware work with either of `HttpRoutes`/`HttpApp` be a good enough solution?

**Comment by vitorsvieira** [comment]
Logger, ResponseLogger, and RequestLogger were also affected.

**Comment by rossabaker** [comment]
I'm reluctant to tailor things specifically to `HttpApp` and `HttpRoutes`, because while those are the big two, those aren't the only two, and I hope people use more.  Auth is another example of something people can compose now in ways that were awkward before.  I'd like a doc that teaches people to read the sigs.

`Timeout` is currently as follows:

```scala
  def apply[F[_], G[_], A](timeout: FiniteDuration, timeoutResponse: F[Response[G]])(
      @deprecatedName('service) http: Kleisli[F, A, Response[G]])(
      implicit F: Concurrent[F],
      T: Timer[F]): Kleisli[F, A, Response[G]]
```

The pain is that we probably have a `Timer[G]` and not a `Timer[F]`.  We could get there with `Timer.derive` given a `Timer[IO]` and a `LiftIO[F]`, but we don't really want `IO` in the signature.  We could also get there with an `G ~> F`, but requiring that extra parameter is unpleasant.  If we had a version specialized to routes, that would have the `G ~> F`, but it kind of fights against the parametricity in the first place.  Conceptually, a `Timeout` on any shape makes sense, but it's definitely hard to use outside `HttpApp`.

The `Logger`s are specialized on `HttpApp`  because they don't conceptually make sense in other effects: we want a total function, so we're not logging things that get recovered to a 4xx by the backend, or combineK'ed into something else.  Their being special is suggestive of them not being great middlewares in the first place, but more appropriate for the backend.

Just thinking out loud here.  I don't have good answers yet, but this is a good discussion.

**Comment by gvolpe** [comment]
A total function on `Logger` makes sense and maybe in other middlewares as well. The separation of concerns sounds neat. The problem I see is that we are pushing this responsibility to the user and makes the API a bit overcomplicated to use. 

Even if we can derive `Timer[G]` from a `Timer[F]` or vice-versa, or provide a natural transformation `F ~> G`, that already makes usage a bit messy and we are losing composition.

I don't really have a clear solution but I think if we want to keep these signatures we should at least provide some high level operations on top of these middlewares to make them compose once again. Eg. provide the needed instances for either `HttpRoutes[F]` or `HttpApp[F]` wherever that makes sense.

**Comment by gvolpe** [comment]
After upgrading to the latest milestone `M3` this is what I'm doing now:

```scala
val middleware: HttpRoutes[F] => HttpApp[F] = {
    { http: HttpRoutes[F] =>
      AutoSlash(http)
    } andThen { http: HttpRoutes[F] =>
      CORS(http, CORS.DefaultCORSConfig)
    } andThen { http: HttpRoutes[F] =>
      Timeout(httpConfig.server.timeout)(http)
    } andThen { http: HttpRoutes[F] =>
      RequestLogger(logHeaders = true, logBody = true)(http.orNotFound)
    } andThen { http: HttpApp[F] =>
      ResponseLogger(logHeaders = true, logBody = true)(http)
    }
  }
```

But I realized I could have done this in previous versions as well. 

Do you find any red flags on this usage @rossabaker ?

**Comment by rossabaker** [comment]
It's a pity that the type inference isn't better, because I would _like_ to write that as:

```scala
    AutoSlash(_) andThen
    CORS(_, CORS.DefaultCORSConfig) andThen
    Timeout(timeout) andThen
    _.orNotFound
    RequestLogger(true, true) andThen
    ResponseLogger(true, true)
```

But I think what you've done is fine.

Did the changes in cats-effect prevent you from needing the ugly `Timer[OptionT[F, ?]]`?  That should be derived from a `Timer[F]` now.

**Comment by gvolpe** [comment]
That's fine, I don't ask the Scala compiler much more :smile: 

Yes, the `Timer` issue seems to be fixed, thanks @rossabaker ! 

Maybe the issue should be closed but I'll leave it open for now since other users have asked about it. I recall @SystemFw being concerned about it too, maybe you want to add something Fabio?

**Comment by rossabaker** [comment]
Make sure we're comfortable with the status quo before 1.0.  Is this still causing people grief?
