### PR TITLE
Log a `Message` body considering the `Entity` model

### PR DESCRIPTION
**Pull request by danicheg**
Sorry for not bringing benchmarks this time, but building a `String` from `Entity.Strtict` directly should have better performance for throughput/memory consumption than building a `Stream` and building a `String` from it.

### CODE REVIEW

File: core/shared/src/main/scala/org/http4s/internal/Logger.scala [hunk 1]
```diff
@@ -37,27 +39,40 @@ object Logger {
...
       }
-      Some(bodyStream.compile.string)
     } else None
 
   def logMessage[F[_]](message: Message[F])(
       logHeaders: Boolean,
       logBody: Boolean,
       redactHeadersWhen: CIString => Boolean = Headers.SensitiveHeaders.contains,
-  )(log: String => F[Unit])(implicit F: Concurrent[F]): F[Unit] = {
+  )(log: String => F[Unit])(implicit F: Async[F]): F[Unit] = {
```
Comment (armanbilge) [inline core/shared/src/main/scala/org/http4s/internal/Logger.scala:75]: Why does this become `Async`? Why do we need `delay` ?

Comment (danicheg) [reply core/shared/src/main/scala/org/http4s/internal/Logger.scala:75]: > Why does this become Async?

Because of `delay`. 

> Why do we need delay ?

It _seems_ like we want to suspend the execution of this effect. Generally, it may not be pure, especially since we give away the responsibility of decoding to a third-party library (even if it's astonishing fs2). And we're not using `blocking` since we believe fs2's decoding isn't thread-blocking.

File: core/shared/src/main/scala/org/http4s/internal/Logger.scala [hunk 2]
```diff
@@ -37,27 +39,40 @@ object Logger {
...
-      } else {
-        message.body.map(b => java.lang.Integer.toHexString(b & 0xff))
+
+      message.entity match {
+        case Entity.Empty =>
+          None
+        case Entity.Strict(bv) =>
+          if (!isBinary || isJson) {
+            val charset = message.charset.fold(Charset.`UTF-8`.nioCharset)(_.nioCharset)
+            Some(F.delay(bv.decodeStringLenient()(charset)))
```
Comment (armanbilge) [inline core/shared/src/main/scala/org/http4s/internal/Logger.scala:57]: Sorry, I guess I'm not really following 😕 how is this an effect? There is no side-effect and it does not throw exception, right?

Comment (danicheg) [reply core/shared/src/main/scala/org/http4s/internal/Logger.scala:57]: > does not throw exception

It shouldn't throw anything if we 100% believe in fs2. But it's decoding... it feels like some things may happen.

Comment (armanbilge) [reply core/shared/src/main/scala/org/http4s/internal/Logger.scala:57]: Even if it did throw an exception, we only need `ApplicativeError.catchNonFatal`.

Anyway, the method is pure. If it throws an exception in some situation, then we should fix it.

https://github.com/scodec/scodec-bits/blob/f9193339783694ed8523d6eb2ab000e73ff8a08d/core/shared/src/main/scala/scodec/bits/ByteVector.scala#L1089-L1106

Comment (danicheg) [reply core/shared/src/main/scala/org/http4s/internal/Logger.scala:57]: Oh Geez, I'm wrong about mentioning `fs2` here. It's from `scodec`.

Comment (danicheg) [reply core/shared/src/main/scala/org/http4s/internal/Logger.scala:57]: Alright, you've convinced me.

**Review by diesalbla — APPROVED** [review]

File: core/shared/src/main/scala/org/http4s/internal/Logger.scala [hunk 3]
```diff
@@ -38,20 +39,33 @@ object Logger {
...
+            val charset = message.charset.fold(Charset.`UTF-8`.nioCharset)(_.nioCharset)
+            Some(F.pure(bv.decodeStringLenient()(charset)))
+          } else
+            Some(F.pure(bv.toHex))
+        case Entity.Default(_, _) =>
+          val stream =
+            if (!isBinary || isJson)
+              message.bodyText
+            else
+              message.body.map(b => java.lang.Integer.toHexString(b & 0xff))
```
Comment (armanbilge) [inline core/shared/src/main/scala/org/http4s/internal/Logger.scala:65]: Is this mapping byte-for-byte? I think it would be more efficient to do `chunk.toByteVector.toHex`.

Comment (danicheg) [reply core/shared/src/main/scala/org/http4s/internal/Logger.scala:65]: Wouldn't it be better to fix it in 0.23 then?

Comment (armanbilge) [reply core/shared/src/main/scala/org/http4s/internal/Logger.scala:65]: You're right!

File: core/shared/src/main/scala/org/http4s/Charset.scala [hunk 4]
```diff
@@ -36,7 +36,7 @@ import java.util.Locale
 import scala.jdk.CollectionConverters._
 
 // scalafix:off Http4sGeneralLinters; bincompat until 1.0
-final case class Charset private (nioCharset: NioCharset) extends Renderable {
+final case class Charset private[http4s] (nioCharset: NioCharset) extends Renderable {
```
[the remark this answers is not in the document]
Comment (danicheg) [reply core/shared/src/main/scala/org/http4s/Charset.scala:39]:
```
core/shared/src/main/scala/org/http4s/Charset.scala:38:1: error: [Http4sGeneralLinters.nonValidatingCopyConstructor] Case classes with private constructors should be abstract to prevent exposing a non-validating copy constructor
[error] final case class Charset private[http4s] (nioCharset: NioCharset) extends Renderable {
[error] ^
[error] (scalafixAll) scalafix.sbt.ScalafixFailed: LinterError
```

**Comment by danicheg** [comment]
@armanbilge is there anything else that should be fixed to get this merged?

**Comment by armanbilge** [comment]
If you don't mind, probably would be better to let the changes in 0.23 bubble up first so we can address the merge conflict in this PR.

**Comment by danicheg** [comment]
I could do the work on merging 0.23 -> main. It's not an issue at all :)

**Review by armanbilge — APPROVED** [review]

**Comment by danicheg** [comment]
@armanbilge and yeah, sorry for nudging you on that.
