### ISSUE TITLE
Discrepancies between 2.10 and 2.11 snapshots

### ISSUE THREAD

**Issue by julien-truffaut** [http4s/http4s#120]
It seems that the client/syntax merged was not built in 2.11. I am getting the following error when using 2.11:

 value prepAs is not a member of org.http4s.client.Client

I don't have this error when I build with scala 2.10
