### ISSUE TITLE
Broken UriParserSpec

### ISSUE THREAD

**Issue by rossabaker** [http4s/http4s#1163]
https://travis-ci.org/http4s/http4s/builds/227293251

```
[error] /home/travis/build/http4s/http4s/tests/src/test/scala/org/http4s/parser/UriParserSpec.scala:39: value toEither is not a member of scala.util.Try[String]
[error]         new IpParser(s, StandardCharsets.UTF_8).CaptureIPv6.run().toEither must beRight(s)
[error]                                                                   ^
[error] /home/travis/build/http4s/http4s/tests/src/test/scala/org/http4s/parser/UriParserSpec.scala:46: value toEither is not a member of scala.util.Try[String]
[error]         new IpParser(addr, StandardCharsets.UTF_8).CaptureIPv4.run().toEither must beRight(addr)
```

Should use `DeliveryScheme.Either` or a `Try => Either` that works in 2.11.  I'm too sleepy to fix this tonight.

**Comment by ChristopherDavenport** [comment]
Got this.
